services:
  db:
    image: postgres
    volumes:
      - dbVol:/var/lib/postgresql/data
    networks:
      - webservice
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./core:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - webservice
networks:
  webservice:
    driver: bridge
volumes:
  dbVol:
  bkVol:
